### ISSUE TITLE
Improvement: There is no possibility to finish all requests without removing credential

### ISSUE THREAD

**Issue by yakovshkolnikov** [dashdevs/AlamofireSessionRenewer#6]
If we receive error by tokens renew - we should call `failureRenewHandler` closure.  In this closure we remove credential and finish all requests. But there are some cases when we need to finish requests without removing credential (if server returns 500 error).
Possible solution: add flag `needsToClearCredential` to `failureRenewHandler` closure.

**Comment by annagorobchenko** [comment]
Should be fixed in 1.0.0
